name: Update Vtubers OPML to Gist

on:
  workflow_dispatch: 

jobs:
  update-gist:
    runs-on: ubuntu-latest

    env:
      NOTION_VTUBERS_DATABASE_API_KEY: ${{ secrets.NOTION_VTUBERS_DATABASE_API_KEY }}
      TOKEN_OF_GITHUB_GIST: ${{ secrets.TOKEN_OF_GITHUB_GIST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --prefix scripts/notion-database-youtube-url-to-opml

      - name: Run update gist script
        run: node scripts/notion-database-youtube-url-to-opml/index.js
